DEFAULT_TIMEFRAME = 60

DEFAULT_CANDLE_COUNT = 100

SUPPORTED_TIMEFRAMES = {
    "1M": 60,
    "5M": 300,
    "15M": 900,
}

MARKET_LIVE = "LIVE"
MARKET_OTC = "OTC"

OTC_SUFFIX = "_otc"

STATUS_CONNECTED = "CONNECTED"
STATUS_DISCONNECTED = "DISCONNECTED"

DEFAULT_RECONNECT_DELAY = 5
DEFAULT_WEBSOCKET_TIMEOUT = 30
